common: &common
  adapter: postgresql

development:
  <<: *common
  database: websocket_chat_dev

test:
  <<: *common
  database: websocket_chat_test

production:
  <<: *common
  database: websocket_chat
