common: &common
  adapter: postgresql
  username: dan
  password: mele4all
  host: localhost

development:
  <<: *common
  database: websocket_chat_dev

test:
  <<: *common
  database: websocket_chat_test

production:
  <<: *common
  database: websocket_chat
